# Copyright 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: skaffold/v4beta14
kind: Config
metadata:
  name: metallb-single-cluster
.metallbHelm: &metallb_helm
  releases:
    - name: metallb
      chartPath: ../../../.cache/helm/metallb-0.15.2.tgz
      namespace: metallb-system
      createNamespace: true
      skipBuildDependencies: true
deploy:
  kubeContext: kind-dsx-exchange
  statusCheck: true
  statusCheckDeadlineSeconds: 600
  helm: *metallb_helm
---
apiVersion: skaffold/v4beta14
kind: Config
metadata:
  name: metallb-config-single-cluster
requires:
  - configs:
      - metallb-single-cluster
manifests:
  rawYaml:
    - ../sites/csc/address-pools.yaml
    - ../sites/cpc-1/address-pools.yaml
    - ../sites/cpc-2/address-pools.yaml
deploy:
  kubeContext: kind-dsx-exchange
  statusCheck: true
  statusCheckDeadlineSeconds: 180
  kubectl: {}
---
apiVersion: skaffold/v4beta14
kind: Config
metadata:
  name: metallb-csc
deploy:
  kubeContext: kind-csc
  statusCheck: true
  statusCheckDeadlineSeconds: 600
  helm: *metallb_helm
---
apiVersion: skaffold/v4beta14
kind: Config
metadata:
  name: metallb-config-csc
requires:
  - configs:
      - metallb-csc
manifests:
  rawYaml:
    - ../sites/csc/address-pools.yaml
deploy:
  kubeContext: kind-csc
  statusCheck: true
  statusCheckDeadlineSeconds: 180
  kubectl: {}
---
apiVersion: skaffold/v4beta14
kind: Config
metadata:
  name: metallb-cpc-1
deploy:
  kubeContext: kind-cpc-1
  statusCheck: true
  statusCheckDeadlineSeconds: 600
  helm: *metallb_helm
---
apiVersion: skaffold/v4beta14
kind: Config
metadata:
  name: metallb-config-cpc-1
requires:
  - configs:
      - metallb-cpc-1
manifests:
  rawYaml:
    - ../sites/cpc-1/address-pools.yaml
deploy:
  kubeContext: kind-cpc-1
  statusCheck: true
  statusCheckDeadlineSeconds: 180
  kubectl: {}
---
apiVersion: skaffold/v4beta14
kind: Config
metadata:
  name: metallb-cpc-2
deploy:
  kubeContext: kind-cpc-2
  statusCheck: true
  statusCheckDeadlineSeconds: 600
  helm: *metallb_helm
---
apiVersion: skaffold/v4beta14
kind: Config
metadata:
  name: metallb-config-cpc-2
requires:
  - configs:
      - metallb-cpc-2
manifests:
  rawYaml:
    - ../sites/cpc-2/address-pools.yaml
deploy:
  kubeContext: kind-cpc-2
  statusCheck: true
  statusCheckDeadlineSeconds: 180
  kubectl: {}
