# Copyright 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: skaffold/v4beta14
kind: Config
metadata:
  name: local-stack
resourceSelector:
  allow:
    - groupKind: "Stream.jetstream.nats.io"
      labels: [".*"]
requires:
  - path: local/skaffold/images.yaml
    configs:
      - local-images
  - path: local/nats/skaffold.yaml
    configs:
      - nats-single-cluster
profiles:
  - name: multi-cluster
    activation:
      - env: MULTI_CLUSTER=1
    patches:
      - op: replace
        path: /requires/1/configs/0
        value: nats-multi-cluster
