# Copyright 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

server = "https://ghcr.io"

[host."http://kind-registry:5000/v2/ghcr.io"]
  capabilities = ["pull", "resolve"]
  override_path = true
