# Copyright 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

image:
  repository: dsx-exchange/demoidp
  tag: latest
  pullPolicy: IfNotPresent

issuers:
  - name: event-bus
  - name: human-oidc
  - name: service-oidc
  - name: svid-issuer
  - name: svid-wrong-key
  - name: unconfigured-issuer
