# Copyright 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: skaffold/v4beta14
kind: Config
metadata:
  name: cert-manager-single-cluster
.certManagerManifests: &cert_manager_manifests
  kustomize:
    paths:
      - .
manifests: *cert_manager_manifests
deploy:
  kubeContext: kind-dsx-exchange
  statusCheck: true
  statusCheckDeadlineSeconds: 300
  kubectl: {}
---
apiVersion: skaffold/v4beta14
kind: Config
metadata:
  name: cert-manager-csc
manifests: *cert_manager_manifests
deploy:
  kubeContext: kind-csc
  statusCheck: true
  statusCheckDeadlineSeconds: 300
  kubectl: {}
---
apiVersion: skaffold/v4beta14
kind: Config
metadata:
  name: cert-manager-cpc-1
manifests: *cert_manager_manifests
deploy:
  kubeContext: kind-cpc-1
  statusCheck: true
  statusCheckDeadlineSeconds: 300
  kubectl: {}
---
apiVersion: skaffold/v4beta14
kind: Config
metadata:
  name: cert-manager-cpc-2
manifests: *cert_manager_manifests
deploy:
  kubeContext: kind-cpc-2
  statusCheck: true
  statusCheckDeadlineSeconds: 300
  kubectl: {}
