# Copyright 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: skaffold/v4beta14
kind: Config
metadata:
  name: cert-manager
manifests:
  kustomize:
    paths:
    - ../cert-manager
    buildArgs:
    - --load-restrictor=LoadRestrictionsNone
deploy:
  statusCheck: true
  statusCheckDeadlineSeconds: 300
  kubectl: {}
