# Copyright 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: ""
generated: "0001-01-01T00:00:00Z"
repositories:
  - caFile: ""
    certFile: ""
    insecure_skip_tls_verify: false
    keyFile: ""
    name: nats
    pass_credentials_all: false
    password: ""
    url: https://nats-io.github.io/k8s/helm/charts/
    username: ""
