# Copyright 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: latinum-mcp-gateway-ratelimit-config
  namespace: mcp-gateway
data:
  mcp-gateway.yaml: |
    domain: mcp-gateway
    descriptors:
      - key: tenant
        rate_limit:
          unit: second
          requests_per_unit: 5000
