# Copyright 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: skaffold/v4beta14
kind: Config
metadata:
  name: infra-csc
requires:
  - configs:
      - infra-csc-controllers
      - infra-csc-config
      - cert-manager-csc
      - keycloak-csc
---
apiVersion: skaffold/v4beta14
kind: Config
metadata:
  name: infra-cpc-1
requires:
  - configs:
      - infra-cpc-1-controllers
      - infra-cpc-1-config
      - cert-manager-cpc-1
---
apiVersion: skaffold/v4beta14
kind: Config
metadata:
  name: infra-cpc-2
requires:
  - configs:
      - infra-cpc-2-controllers
      - infra-cpc-2-config
      - cert-manager-cpc-2
---
apiVersion: skaffold/v4beta14
kind: Config
metadata:
  name: envoy-gateway-crds-csc
manifests:
  helm:
    releases:
      - name: eg-crds
        remoteChart: oci://docker.io/envoyproxy/gateway-crds-helm
        version: v1.5.4
        namespace: envoy-gateway-system
        setValues:
          crds.gatewayAPI.enabled: true
          crds.gatewayAPI.channel: experimental
          crds.envoyGateway.enabled: true
deploy:
  kubeContext: kind-csc
  statusCheck: true
  statusCheckDeadlineSeconds: 300
  kubectl:
    flags:
      apply:
        - --server-side
---
apiVersion: skaffold/v4beta14
kind: Config
metadata:
  name: envoy-gateway-crds-cpc-1
manifests:
  helm:
    releases:
      - name: eg-crds
        remoteChart: oci://docker.io/envoyproxy/gateway-crds-helm
        version: v1.5.4
        namespace: envoy-gateway-system
        setValues:
          crds.gatewayAPI.enabled: true
          crds.gatewayAPI.channel: experimental
          crds.envoyGateway.enabled: true
deploy:
  kubeContext: kind-cpc-1
  statusCheck: true
  statusCheckDeadlineSeconds: 300
  kubectl:
    flags:
      apply:
        - --server-side
---
apiVersion: skaffold/v4beta14
kind: Config
metadata:
  name: envoy-gateway-crds-cpc-2
manifests:
  helm:
    releases:
      - name: eg-crds
        remoteChart: oci://docker.io/envoyproxy/gateway-crds-helm
        version: v1.5.4
        namespace: envoy-gateway-system
        setValues:
          crds.gatewayAPI.enabled: true
          crds.gatewayAPI.channel: experimental
          crds.envoyGateway.enabled: true
deploy:
  kubeContext: kind-cpc-2
  statusCheck: true
  statusCheckDeadlineSeconds: 300
  kubectl:
    flags:
      apply:
        - --server-side
---
apiVersion: skaffold/v4beta14
kind: Config
metadata:
  name: cert-manager-csc
manifests:
  kustomize:
    paths:
      - cert-manager
deploy:
  kubeContext: kind-csc
  statusCheck: true
  statusCheckDeadlineSeconds: 300
  kubectl: {}
---
apiVersion: skaffold/v4beta14
kind: Config
metadata:
  name: cert-manager-cpc-1
manifests:
  kustomize:
    paths:
      - cert-manager
deploy:
  kubeContext: kind-cpc-1
  statusCheck: true
  statusCheckDeadlineSeconds: 300
  kubectl: {}
---
apiVersion: skaffold/v4beta14
kind: Config
metadata:
  name: cert-manager-cpc-2
manifests:
  kustomize:
    paths:
      - cert-manager
deploy:
  kubeContext: kind-cpc-2
  statusCheck: true
  statusCheckDeadlineSeconds: 300
  kubectl: {}
---
apiVersion: skaffold/v4beta14
kind: Config
metadata:
  name: infra-csc-controllers
requires:
  - configs:
      - envoy-gateway-crds-csc
deploy:
  kubeContext: kind-csc
  statusCheck: true
  statusCheckDeadlineSeconds: 600
  helm:
    concurrency: 4
    releases:
      - name: metallb
        remoteChart: metallb
        repo: https://metallb.github.io/metallb
        version: 0.15.2
        namespace: metallb-system
        createNamespace: true
        upgradeOnChange: true
      - name: eg
        remoteChart: oci://docker.io/envoyproxy/gateway-helm
        version: v1.5.4
        namespace: envoy-gateway-system
        createNamespace: true
        upgradeOnChange: true
      - name: metrics-server
        remoteChart: metrics-server
        repo: https://kubernetes-sigs.github.io/metrics-server/
        version: 3.13.0
        namespace: kube-system
        setValues:
          image.tag: v0.8.1
          args[0]: --kubelet-insecure-tls
        upgradeOnChange: true
      - name: prometheus
        remoteChart: kube-prometheus-stack
        repo: https://prometheus-community.github.io/helm-charts
        version: 86.1.0
        namespace: monitoring
        createNamespace: true
        valuesFiles:
          - prometheus/values.yaml
        upgradeOnChange: true
---
apiVersion: skaffold/v4beta14
kind: Config
metadata:
  name: infra-cpc-1-controllers
requires:
  - configs:
      - envoy-gateway-crds-cpc-1
deploy:
  kubeContext: kind-cpc-1
  statusCheck: true
  statusCheckDeadlineSeconds: 600
  helm:
    concurrency: 4
    releases:
      - name: metallb
        remoteChart: metallb
        repo: https://metallb.github.io/metallb
        version: 0.15.2
        namespace: metallb-system
        createNamespace: true
        upgradeOnChange: true
      - name: eg
        remoteChart: oci://docker.io/envoyproxy/gateway-helm
        version: v1.5.4
        namespace: envoy-gateway-system
        createNamespace: true
        upgradeOnChange: true
      - name: metrics-server
        remoteChart: metrics-server
        repo: https://kubernetes-sigs.github.io/metrics-server/
        version: 3.13.0
        namespace: kube-system
        setValues:
          image.tag: v0.8.1
          args[0]: --kubelet-insecure-tls
        upgradeOnChange: true
      - name: prometheus
        remoteChart: kube-prometheus-stack
        repo: https://prometheus-community.github.io/helm-charts
        version: 86.1.0
        namespace: monitoring
        createNamespace: true
        valuesFiles:
          - prometheus/values.yaml
        upgradeOnChange: true
---
apiVersion: skaffold/v4beta14
kind: Config
metadata:
  name: infra-cpc-2-controllers
requires:
  - configs:
      - envoy-gateway-crds-cpc-2
deploy:
  kubeContext: kind-cpc-2
  statusCheck: true
  statusCheckDeadlineSeconds: 600
  helm:
    concurrency: 4
    releases:
      - name: metallb
        remoteChart: metallb
        repo: https://metallb.github.io/metallb
        version: 0.15.2
        namespace: metallb-system
        createNamespace: true
        upgradeOnChange: true
      - name: eg
        remoteChart: oci://docker.io/envoyproxy/gateway-helm
        version: v1.5.4
        namespace: envoy-gateway-system
        createNamespace: true
        upgradeOnChange: true
      - name: metrics-server
        remoteChart: metrics-server
        repo: https://kubernetes-sigs.github.io/metrics-server/
        version: 3.13.0
        namespace: kube-system
        setValues:
          image.tag: v0.8.1
          args[0]: --kubelet-insecure-tls
        upgradeOnChange: true
      - name: prometheus
        remoteChart: kube-prometheus-stack
        repo: https://prometheus-community.github.io/helm-charts
        version: 86.1.0
        namespace: monitoring
        createNamespace: true
        valuesFiles:
          - prometheus/values.yaml
        upgradeOnChange: true
---
apiVersion: skaffold/v4beta14
kind: Config
metadata:
  name: infra-csc-config
requires:
  - configs:
      - infra-csc-controllers
manifests:
  rawYaml:
    - metallb/csc-pool.yaml
    - envoy-gateway/gatewayclass.yaml
    - envoy-gateway/gateway.yaml
deploy:
  kubeContext: kind-csc
  statusCheck: true
  statusCheckDeadlineSeconds: 180
  kubectl: {}
---
apiVersion: skaffold/v4beta14
kind: Config
metadata:
  name: infra-cpc-1-config
requires:
  - configs:
      - infra-cpc-1-controllers
manifests:
  rawYaml:
    - metallb/cpc-1-pool.yaml
    - envoy-gateway/gatewayclass.yaml
    - envoy-gateway/gateway.yaml
deploy:
  kubeContext: kind-cpc-1
  statusCheck: true
  statusCheckDeadlineSeconds: 180
  kubectl: {}
---
apiVersion: skaffold/v4beta14
kind: Config
metadata:
  name: infra-cpc-2-config
requires:
  - configs:
      - infra-cpc-2-controllers
manifests:
  rawYaml:
    - metallb/cpc-2-pool.yaml
    - envoy-gateway/gatewayclass.yaml
    - envoy-gateway/gateway.yaml
deploy:
  kubeContext: kind-cpc-2
  statusCheck: true
  statusCheckDeadlineSeconds: 180
  kubectl: {}
---
apiVersion: skaffold/v4beta14
kind: Config
metadata:
  name: keycloak-operator-csc
manifests:
  kustomize:
    paths:
      - keycloak/operator
deploy:
  kubeContext: kind-csc
  statusCheck: true
  statusCheckDeadlineSeconds: 300
  kubectl: {}
---
apiVersion: skaffold/v4beta14
kind: Config
metadata:
  name: keycloak-csc
requires:
  - configs:
      - keycloak-operator-csc
      - infra-csc-config
manifests:
  rawYaml:
    - keycloak/realm-import.yaml
    - keycloak/keycloak.yaml
    - keycloak/httproute.yaml
deploy:
  kubeContext: kind-csc
  statusCheck: true
  statusCheckDeadlineSeconds: 600
  kubectl: {}
