# Copyright 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: skaffold/v4beta14
kind: Config
metadata:
  name: infra-single-cluster
requires:
  - path: cert-manager/skaffold.yaml
    configs:
      - cert-manager-single-cluster
  - path: metrics-server/skaffold.yaml
    configs:
      - metrics-server-single-cluster
  - path: prometheus/skaffold.yaml
    configs:
      - prometheus-single-cluster
  - path: keycloak/skaffold.yaml
    configs:
      - keycloak-single-cluster
  - path: sites/skaffold.yaml
    configs:
      - site-cpc-1-single-cluster
      - site-cpc-2-single-cluster
---
apiVersion: skaffold/v4beta14
kind: Config
metadata:
  name: infra-csc
requires:
  - path: cert-manager/skaffold.yaml
    configs:
      - cert-manager-csc
  - path: metrics-server/skaffold.yaml
    configs:
      - metrics-server-csc
  - path: prometheus/skaffold.yaml
    configs:
      - prometheus-csc
  - path: keycloak/skaffold.yaml
    configs:
      - keycloak-csc
---
apiVersion: skaffold/v4beta14
kind: Config
metadata:
  name: infra-cpc-1
requires:
  - path: cert-manager/skaffold.yaml
    configs:
      - cert-manager-cpc-1
  - path: metrics-server/skaffold.yaml
    configs:
      - metrics-server-cpc-1
  - path: prometheus/skaffold.yaml
    configs:
      - prometheus-cpc-1
  - path: sites/skaffold.yaml
    configs:
      - site-cpc-1-multi-cluster
---
apiVersion: skaffold/v4beta14
kind: Config
metadata:
  name: infra-cpc-2
requires:
  - path: cert-manager/skaffold.yaml
    configs:
      - cert-manager-cpc-2
  - path: metrics-server/skaffold.yaml
    configs:
      - metrics-server-cpc-2
  - path: prometheus/skaffold.yaml
    configs:
      - prometheus-cpc-2
  - path: sites/skaffold.yaml
    configs:
      - site-cpc-2-multi-cluster
