# Copyright 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: skaffold/v4beta14
kind: Config
metadata:
  name: nats-secret-sources
manifests:
  hooks:
    before:
      - host:
          command:
            - sh
            - -c
            - local/nats/prepare-secrets.sh
---
apiVersion: skaffold/v4beta14
kind: Config
metadata:
  name: nats-secrets-single-cluster
requires:
  - configs:
      - nats-secret-sources
manifests:
  kustomize:
    paths:
      - k8s/secret-generators/csc
      - k8s/secret-generators/cpc-1
      - k8s/secret-generators/cpc-2
    buildArgs:
      - --load-restrictor=LoadRestrictionsNone
deploy:
  kubeContext: kind-dsx-exchange
  statusCheck: true
  statusCheckDeadlineSeconds: 180
  kubectl: {}
---
apiVersion: skaffold/v4beta14
kind: Config
metadata:
  name: nats-secrets-csc
requires:
  - configs:
      - nats-secret-sources
manifests:
  kustomize:
    paths:
      - k8s/secret-generators/csc
    buildArgs:
      - --load-restrictor=LoadRestrictionsNone
deploy:
  kubeContext: kind-csc
  statusCheck: true
  statusCheckDeadlineSeconds: 180
  kubectl: {}
---
apiVersion: skaffold/v4beta14
kind: Config
metadata:
  name: nats-secrets-cpc-1
requires:
  - configs:
      - nats-secret-sources
manifests:
  kustomize:
    paths:
      - k8s/secret-generators/cpc-1
    buildArgs:
      - --load-restrictor=LoadRestrictionsNone
deploy:
  kubeContext: kind-cpc-1
  statusCheck: true
  statusCheckDeadlineSeconds: 180
  kubectl: {}
---
apiVersion: skaffold/v4beta14
kind: Config
metadata:
  name: nats-secrets-cpc-2
requires:
  - configs:
      - nats-secret-sources
manifests:
  kustomize:
    paths:
      - k8s/secret-generators/cpc-2
    buildArgs:
      - --load-restrictor=LoadRestrictionsNone
deploy:
  kubeContext: kind-cpc-2
  statusCheck: true
  statusCheckDeadlineSeconds: 180
  kubectl: {}
