# Copyright 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: skaffold/v4beta14
kind: Config
metadata:
  name: nats-sites-single-cluster
.natsReleaseBase: &nats_release_base
  chartPath: ../../deploy/nats-event-bus
  createNamespace: true
  wait: true
  skipBuildDependencies: true
  setValues:
    auth-callout.image.repository: localhost:5001/auth-callout
    auth-callout.image.tag: local
    auth-callout.image.pullPolicy: IfNotPresent
requires:
  - path: ../skaffold/images.yaml
    configs:
      - local-images
  - path: skaffold.secrets.yaml
    configs:
      - nats-secrets-single-cluster
  - path: ../infra/skaffold.yaml
    configs:
      - infra-single-cluster
deploy:
  kubeContext: kind-dsx-exchange
  statusCheck: true
  statusCheckDeadlineSeconds: 600
  tolerateFailuresUntilDeadline: true
  helm:
    concurrency: 0
    releases:
      - <<: *nats_release_base
        name: nats-event-bus-csc
        namespace: csc-event-bus
        valuesFiles:
          - k8s/local-dev-values.yaml
          - k8s/csc/values.yaml
      - <<: *nats_release_base
        name: nats-event-bus-cpc-1
        namespace: cpc-1-event-bus
        valuesFiles:
          - k8s/local-dev-values.yaml
          - k8s/cpc/values.yaml
          - k8s/cpc/cpc-1.yaml
      - <<: *nats_release_base
        name: nats-event-bus-cpc-2
        namespace: cpc-2-event-bus
        valuesFiles:
          - k8s/local-dev-values.yaml
          - k8s/cpc/values.yaml
          - k8s/cpc/cpc-2.yaml
---
apiVersion: skaffold/v4beta14
kind: Config
metadata:
  name: nats-csc
requires:
  - path: ../skaffold/images.yaml
    configs:
      - local-images
  - path: skaffold.secrets.yaml
    configs:
      - nats-secrets-csc
  - path: ../infra/skaffold.yaml
    configs:
      - infra-csc
deploy:
  kubeContext: kind-csc
  statusCheck: true
  statusCheckDeadlineSeconds: 600
  tolerateFailuresUntilDeadline: true
  helm:
    releases:
      - <<: *nats_release_base
        name: nats-event-bus-csc
        namespace: csc-event-bus
        valuesFiles:
          - k8s/local-dev-values.yaml
          - k8s/csc/values.yaml
---
apiVersion: skaffold/v4beta14
kind: Config
metadata:
  name: nats-cpc-1
requires:
  - path: ../skaffold/images.yaml
    configs:
      - local-images
  - path: skaffold.secrets.yaml
    configs:
      - nats-secrets-cpc-1
  - path: ../infra/skaffold.yaml
    configs:
      - infra-cpc-1
deploy:
  kubeContext: kind-cpc-1
  statusCheck: true
  statusCheckDeadlineSeconds: 600
  tolerateFailuresUntilDeadline: true
  helm:
    releases:
      - <<: *nats_release_base
        name: nats-event-bus-cpc-1
        namespace: cpc-1-event-bus
        valuesFiles:
          - k8s/local-dev-values.yaml
          - k8s/cpc/values.yaml
          - k8s/cpc/cpc-1.yaml
---
apiVersion: skaffold/v4beta14
kind: Config
metadata:
  name: nats-cpc-2
requires:
  - path: ../skaffold/images.yaml
    configs:
      - local-images
  - path: skaffold.secrets.yaml
    configs:
      - nats-secrets-cpc-2
  - path: ../infra/skaffold.yaml
    configs:
      - infra-cpc-2
deploy:
  kubeContext: kind-cpc-2
  statusCheck: true
  statusCheckDeadlineSeconds: 600
  tolerateFailuresUntilDeadline: true
  helm:
    releases:
      - <<: *nats_release_base
        name: nats-event-bus-cpc-2
        namespace: cpc-2-event-bus
        valuesFiles:
          - k8s/local-dev-values.yaml
          - k8s/cpc/values.yaml
          - k8s/cpc/cpc-2.yaml
