# Copyright 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: skaffold/v4beta14
kind: Config
metadata:
  name: auth-callout-image
build:
  tagPolicy:
    envTemplate:
      template: local
  local:
    push: true
    tryImportMissing: true
    useDockerCLI: true
    useBuildkit: true
  artifacts:
    - image: localhost:5001/auth-callout
      context: ../../auth-callout
      docker:
        dockerfile: build/package/Dockerfile
        cliFlags:
          - --provenance=false
---
apiVersion: skaffold/v4beta14
kind: Config
metadata:
  name: nats
requires:
  - configs:
      - auth-callout-image
  - path: ../infra/skaffold.yaml
    configs:
      - infra
deploy:
  kubeContext: kind-csc
  statusCheck: true
  statusCheckDeadlineSeconds: 600
  tolerateFailuresUntilDeadline: true
  helm:
    flags:
      depBuild:
        - --repository-config=local/helm/repositories.yaml
    hooks:
      before:
        - host:
            command:
              - sh
              - -c
              - local/nats/prepare-secrets.sh csc
    releases:
      - name: nats-event-bus
        chartPath: ../../deploy/nats-event-bus
        namespace: event-bus
        createNamespace: true
        valuesFiles:
          - k8s/local-dev-values.yaml
          - k8s/csc/values.yaml
        setValues:
          auth-callout.image.repository: localhost:5001/auth-callout
          auth-callout.image.tag: local
          auth-callout.image.pullPolicy: Always
profiles:
  - name: cpc-1
    patches:
      - op: replace
        path: /deploy/kubeContext
        value: kind-cpc-1
      - op: replace
        path: /deploy/helm/hooks/before/0/host/command/2
        value: local/nats/prepare-secrets.sh cpc-1
      - op: replace
        path: /deploy/helm/releases/0/valuesFiles
        value:
          - k8s/local-dev-values.yaml
          - k8s/cpc/values.yaml
          - k8s/cpc/cpc-1.yaml
  - name: cpc-2
    patches:
      - op: replace
        path: /deploy/kubeContext
        value: kind-cpc-2
      - op: replace
        path: /deploy/helm/hooks/before/0/host/command/2
        value: local/nats/prepare-secrets.sh cpc-2
      - op: replace
        path: /deploy/helm/releases/0/valuesFiles
        value:
          - k8s/local-dev-values.yaml
          - k8s/cpc/values.yaml
          - k8s/cpc/cpc-2.yaml
