# Copyright 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: skaffold/v4beta14
kind: Config
metadata:
  name: envoy-gateway-crds
requires:
- path: ../gateway-api/skaffold.yaml
  configs:
  - gateway-api-crds
manifests:
  helm:
    releases:
    - name: eg-crds
      chartPath: ../../../.cache/helm/gateway-crds-helm-v1.8.3.tgz
      namespace: envoy-gateway-system
      createNamespace: true
      skipBuildDependencies: true
      setValues:
        crds.gatewayAPI.enabled: false
        crds.envoyGateway.enabled: true
deploy:
  statusCheck: true
  statusCheckDeadlineSeconds: 300
  kubectl:
    flags:
      apply:
      - --server-side
---
apiVersion: skaffold/v4beta14
kind: Config
metadata:
  name: envoy-gateway
requires:
- path: ../metallb/skaffold.yaml
  configs:
  - metallb-config
- configs:
  - envoy-gateway-crds
deploy:
  statusCheck: true
  statusCheckDeadlineSeconds: 600
  helm:
    hooks:
      before:
      - host:
          command:
          - kubectl
          - --context
          - kind-dsx-exchange
          - wait
          - --for=condition=Established
          - --timeout=60s
          - crd/tlsroutes.gateway.networking.k8s.io
    flags:
      install:
      - --skip-crds
      upgrade:
      - --skip-crds
    releases:
    - name: eg
      chartPath: ../../../.cache/helm/gateway-helm-v1.8.3.tgz
      namespace: envoy-gateway-system
      createNamespace: true
      skipBuildDependencies: true
      valuesFiles:
      - ../envoy-gateway/values.yaml
---
apiVersion: skaffold/v4beta14
kind: Config
metadata:
  name: envoy-gateway-class
requires:
- configs:
  - envoy-gateway
manifests:
  rawYaml:
  - ../envoy-gateway/gatewayclass.yaml
deploy:
  statusCheck: true
  statusCheckDeadlineSeconds: 180
  kubectl: {}
