# Copyright 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: skaffold/v4beta14
kind: Config
metadata:
  name: prometheus-single-cluster
.prometheusHelm: &prometheus_helm
  releases:
    - name: prometheus
      chartPath: ../../../.cache/helm/kube-prometheus-stack-86.1.0.tgz
      namespace: monitoring
      createNamespace: true
      skipBuildDependencies: true
      valuesFiles:
        - values.yaml
deploy:
  kubeContext: kind-dsx-exchange
  statusCheck: true
  statusCheckDeadlineSeconds: 600
  helm: *prometheus_helm
---
apiVersion: skaffold/v4beta14
kind: Config
metadata:
  name: prometheus-csc
deploy:
  kubeContext: kind-csc
  statusCheck: true
  statusCheckDeadlineSeconds: 600
  helm: *prometheus_helm
---
apiVersion: skaffold/v4beta14
kind: Config
metadata:
  name: prometheus-cpc-1
deploy:
  kubeContext: kind-cpc-1
  statusCheck: true
  statusCheckDeadlineSeconds: 600
  helm: *prometheus_helm
---
apiVersion: skaffold/v4beta14
kind: Config
metadata:
  name: prometheus-cpc-2
deploy:
  kubeContext: kind-cpc-2
  statusCheck: true
  statusCheckDeadlineSeconds: 600
  helm: *prometheus_helm
