# Copyright 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: keycloak-realm-import
    namespace: keycloak
    files:
      - realm-event-bus.json
generatorOptions:
  disableNameSuffixHash: true
resources:
  - keycloak.yaml
  - httproute.yaml
