# Copyright 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: skaffold/v4beta14
kind: Config
metadata:
  name: keycloak-operator-single-cluster
.keycloakOperatorManifests: &keycloak_operator_manifests
  kustomize:
    paths:
      - operator
.keycloakManifests: &keycloak_manifests
  rawYaml:
    - realm-import.yaml
    - keycloak.yaml
    - httproute.yaml
manifests: *keycloak_operator_manifests
deploy:
  kubeContext: kind-dsx-exchange
  statusCheck: true
  statusCheckDeadlineSeconds: 300
  kubectl: {}
---
apiVersion: skaffold/v4beta14
kind: Config
metadata:
  name: keycloak-single-cluster
requires:
  - configs:
      - keycloak-operator-single-cluster
  - path: ../sites/skaffold.yaml
    configs:
      - site-csc-single-cluster
manifests: *keycloak_manifests
deploy:
  kubeContext: kind-dsx-exchange
  statusCheck: true
  statusCheckDeadlineSeconds: 600
  kubectl: {}
---
apiVersion: skaffold/v4beta14
kind: Config
metadata:
  name: keycloak-operator-csc
manifests: *keycloak_operator_manifests
deploy:
  kubeContext: kind-csc
  statusCheck: true
  statusCheckDeadlineSeconds: 300
  kubectl: {}
---
apiVersion: skaffold/v4beta14
kind: Config
metadata:
  name: keycloak-csc
requires:
  - configs:
      - keycloak-operator-csc
  - path: ../sites/skaffold.yaml
    configs:
      - site-csc-multi-cluster
manifests: *keycloak_manifests
deploy:
  kubeContext: kind-csc
  statusCheck: true
  statusCheckDeadlineSeconds: 600
  kubectl: {}
