# Copyright 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: skaffold/v4beta14
kind: Config
metadata:
  name: keycloak-operator
manifests:
  kustomize:
    paths:
    - ../keycloak/operator
    buildArgs:
    - --load-restrictor=LoadRestrictionsNone
deploy:
  statusCheck: true
  statusCheckDeadlineSeconds: 300
  kubectl: {}
---
apiVersion: skaffold/v4beta14
kind: Config
metadata:
  name: keycloak
requires:
- configs:
  - keycloak-operator
- path: ../sites/skaffold.yaml
  configs:
  - sites
manifests:
  rawYaml:
  - ../keycloak/realm-import.yaml
  - ../keycloak/keycloak.yaml
  - ../keycloak/httproute.yaml
deploy:
  statusCheck: true
  statusCheckDeadlineSeconds: 600
  kubectl: {}
